// TTP - Talk To Paste
// In-app uninstall. Wipes keychain entries that only the running app can
// reach via the `keyring` crate, then spawns a detached shell script that
// waits for the app to quit and removes the .app, config dir, LaunchAgent,
// WebKit caches, and resets the macOS TCC permissions.
//
// Why a detached script: a running process can't delete its own .app bundle
// while it's executing. The classic macOS pattern is to spawn a helper that
// outlives the parent, sleeps a beat, and then nukes the bundle.

#[cfg(target_os = "macos")]
use std::fs;
#[cfg(target_os = "macos")]
use std::os::unix::fs::PermissionsExt;
#[cfg(target_os = "macos")]
use std::process::Command;

const BUNDLE_ID: &str = "com.ttp.desktop";
const APP_NAME: &str = "TTP by AmirKS";
const CONFIG_NAME: &str = "ttp";

/// macOS-only. Wipes keychain + spawns detached uninstaller + quits app.
#[tauri::command]
pub fn uninstall_app(app: tauri::AppHandle) -> Result<(), String> {
    #[cfg(not(target_os = "macos"))]
    {
        let _ = app;
        return Err("In-app uninstall is currently macOS-only. Use Add or Remove Programs (Windows) or remove the bundle and ~/.config/ttp manually (Linux).".into());
    }
    #[cfg(target_os = "macos")]
    {
        // 1. Keychain — easier to wipe from inside the app via the keyring crate
        //    than from the shell script, which would need `security delete-
        //    generic-password` and the user's keychain unlocked. Best-effort:
        //    failures here don't block the rest of the uninstall.
        for account in ["groq_api_key", "license_hmac_secret", "usage_hmac_secret"] {
            if let Ok(entry) = keyring::Entry::new(BUNDLE_ID, account) {
                let _ = entry.delete_credential();
            }
        }

        // 2. Write the detached uninstaller script to /tmp.
        let script_path = "/tmp/ttp-uninstall.sh";
        fs::write(script_path, uninstaller_script())
            .map_err(|e| format!("Failed to write uninstaller script: {}", e))?;
        let mut perms = fs::metadata(script_path)
            .map_err(|e| format!("Failed to stat uninstaller script: {}", e))?
            .permissions();
        perms.set_mode(0o755);
        fs::set_permissions(script_path, perms)
            .map_err(|e| format!("Failed to chmod uninstaller script: {}", e))?;

        // 3. Spawn detached. setsid + nohup so the script outlives the parent
        //    app, even when launchctl reaps the running TTP process.
        Command::new("/bin/sh")
            .arg("-c")
            .arg(format!("nohup /bin/bash {} > /tmp/ttp-uninstall.log 2>&1 &", script_path))
            .spawn()
            .map_err(|e| format!("Failed to spawn uninstaller: {}", e))?;

        // 4. Give the spawn a beat to land, then quit. The script's first
        //    action is `sleep 2` so we have plenty of margin.
        std::thread::sleep(std::time::Duration::from_millis(150));
        app.exit(0);
        Ok(())
    }
}

#[cfg(target_os = "macos")]
fn uninstaller_script() -> String {
    format!(
        r#"#!/usr/bin/env bash
# Auto-generated by TTP's in-app uninstaller. Safe to run by hand if you
# want to inspect what's about to happen — comment out `set -e` first.
set -u
exec >> /tmp/ttp-uninstall.log 2>&1
echo "[$(date '+%H:%M:%S')] ttp uninstaller starting"

# Wait for the app to fully quit so we can remove its bundle.
sleep 2
# Belt-and-suspenders kill in case the app didn't exit cleanly.
pkill -fi "{app}" 2>/dev/null || true
sleep 1

# 1. The .app bundle itself.
rm -rf "/Applications/{app}.app" 2>/dev/null || true

# 2. Config dir (settings / usage / dictionary / history / license / last-seen-version).
rm -rf "$HOME/Library/Application Support/{config}" 2>/dev/null || true

# 3. Tauri runtime + WebKit caches keyed by bundle id.
for path in \
  "$HOME/Library/Application Support/{bid}" \
  "$HOME/Library/Caches/{bid}" \
  "$HOME/Library/WebKit/{bid}" \
  "$HOME/Library/HTTPStorages/{bid}" \
  "$HOME/Library/HTTPStorages/{bid}.binarycookies" \
  "$HOME/Library/Preferences/{bid}.plist" \
  "$HOME/Library/Saved Application State/{bid}.savedState" \
; do
  [ -e "$path" ] && rm -rf "$path"
done

# 4. LaunchAgent (autostart). Unload first or launchd will resurrect it.
for plist in "$HOME/Library/LaunchAgents/{bid}.plist" \
             "$HOME/Library/LaunchAgents/{app}.plist"; do
  if [ -f "$plist" ]; then
    launchctl unload "$plist" 2>/dev/null || true
    rm -f "$plist"
  fi
done

# 5. macOS TCC permissions (Mic / Accessibility / Input Monitoring). A future
#    install will re-prompt cleanly.
for service in Microphone Accessibility ListenEvent PostEvent; do
  tccutil reset "$service" "{bid}" >/dev/null 2>&1 || true
done

echo "[$(date '+%H:%M:%S')] ttp uninstaller done"
exit 0
"#,
        app = APP_NAME,
        bid = BUNDLE_ID,
        config = CONFIG_NAME,
    )
}
